#!/usr/bin/env bash
# Copyright 2026 Daniel Tyukov
# SPDX-License-Identifier: Apache-2.0
#
# Fetch the IHP SG13G2 views this repository can use.
#
# The PDK is not vendored here: it is a large Apache-2.0 licensed third party
# artefact with its own release cadence, and committing a copy would make this
# repository stale the moment IHP tags a new version. This script downloads exactly
# the files the flow needs into pdk/ (which .gitignore excludes) and prints the
# environment variables to export.
#
# Usage:
#   tools/fetch_pdk.sh              # sparse clone, just the views the flow reads
#   tools/fetch_pdk.sh --full       # full clone, if you want the whole PDK
#
# After it finishes:
#   export SG13G2_LIB=...           # make synth-pdk
#   export SG13G2_TECH_LEF=...      # make flow
#   export SG13G2_CELL_LEF=...

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PDK_DIR="${PDK_DIR:-$REPO_ROOT/pdk}"
PDK_URL="${PDK_URL:-https://github.com/IHP-GmbH/IHP-Open-PDK.git}"
PDK_REF="${PDK_REF:-main}"
FULL=0

for arg in "$@"; do
  case "$arg" in
    --full) FULL=1 ;;
    -h|--help) sed -n '2,26p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

if ! command -v git >/dev/null 2>&1; then
  echo "fetch_pdk: git is required" >&2
  exit 1
fi

mkdir -p "$PDK_DIR"

if [ -d "$PDK_DIR/IHP-Open-PDK/.git" ]; then
  echo "fetch_pdk: updating the existing checkout in $PDK_DIR/IHP-Open-PDK"
  git -C "$PDK_DIR/IHP-Open-PDK" fetch --depth 1 origin "$PDK_REF"
  git -C "$PDK_DIR/IHP-Open-PDK" checkout FETCH_HEAD
elif [ "$FULL" = "1" ]; then
  git clone --depth 1 --branch "$PDK_REF" "$PDK_URL" "$PDK_DIR/IHP-Open-PDK"
else
  # Sparse checkout of the standard cell views only. The full PDK is several
  # gigabytes; the flow needs a few tens of megabytes of it.
  git clone --depth 1 --filter=blob:none --sparse --branch "$PDK_REF" \
    "$PDK_URL" "$PDK_DIR/IHP-Open-PDK"
  git -C "$PDK_DIR/IHP-Open-PDK" sparse-checkout set \
    ihp-sg13g2/libs.ref/sg13g2_stdcell \
    ihp-sg13g2/libs.ref/sg13g2_io \
    ihp-sg13g2/libs.tech/openroad
fi

CHECKOUT="$PDK_DIR/IHP-Open-PDK/ihp-sg13g2"

find_one() {
  local pattern="$1"
  find "$CHECKOUT" -name "$pattern" -type f 2>/dev/null | head -1
}

LIB="$(find_one 'sg13g2_stdcell_typ_1p20V_25C.lib')"
TECH_LEF="$(find_one 'sg13g2_tech.lef')"
CELL_LEF="$(find_one 'sg13g2_stdcell.lef')"
IO_LEF="$(find_one 'sg13g2_io.lef')"

echo ""
echo "fetch_pdk: found"
printf '  %-16s %s\n' "liberty"  "${LIB:-NOT FOUND}"
printf '  %-16s %s\n' "tech LEF" "${TECH_LEF:-NOT FOUND}"
printf '  %-16s %s\n' "cell LEF" "${CELL_LEF:-NOT FOUND}"
printf '  %-16s %s\n' "IO LEF"   "${IO_LEF:-NOT FOUND (optional)}"

if [ -z "${LIB:-}" ]; then
  echo ""
  echo "fetch_pdk: the liberty file was not found. The PDK layout may have changed;" >&2
  echo "           look under $CHECKOUT and set SG13G2_LIB by hand." >&2
  exit 1
fi

ENV_FILE="$PDK_DIR/env.sh"
{
  echo "# Generated by tools/fetch_pdk.sh"
  echo "export SG13G2_LIB=\"$LIB\""
  [ -n "${TECH_LEF:-}" ] && echo "export SG13G2_TECH_LEF=\"$TECH_LEF\""
  [ -n "${CELL_LEF:-}" ] && echo "export SG13G2_CELL_LEF=\"$CELL_LEF\""
  [ -n "${IO_LEF:-}" ]   && echo "export SG13G2_IO_LEF=\"$IO_LEF\""
} > "$ENV_FILE"

echo ""
echo "fetch_pdk: wrote $ENV_FILE"
echo "  source $ENV_FILE && make synth-pdk"
