#!/usr/bin/env python3
# Copyright 2026 Daniel Tyukov
# SPDX-License-Identifier: Apache-2.0
"""Make the IHP SG13G2 Verilog cell models simulate in Icarus Verilog.

Two edits, and the second one is not optional.

1. Remove the `specify` blocks. They contain `ifnone` edge-sensitive paths, which
   Icarus cannot parse: "sorry: ifnone with an edge-sensitive path is not supported".

2. Drive the `delayed_*` nets. This is the part that is easy to get wrong, and getting
   it wrong is silent. The models do not use their ports directly; they route function
   through timing-check output nets:

       wire delayed_D, delayed_RESET_B, delayed_CLK;
       ...
       ihp_dff_r (int_fwire_IQ, notifier, delayed_CLK, delayed_D, int_fwire_r, xcr_0);

   Those nets are driven by the `$setuphold` and `$recrem` checks inside the specify
   block. Delete the specify block and nothing drives them: every flip-flop stops
   clocking and the whole netlist reads as zero, with no error and no warning. So for
   every `delayed_X` the module declares, this adds `assign delayed_X = X;`.

   That is what a zero-delay functional simulation of these cells should do anyway.
   What is lost is only the pin-to-pin delay annotation, which Icarus could not use
   without SDF back-annotation regardless.

The consequence is documented in docs/PPA_METHODOLOGY.md: the gate level simulation is
zero-delay, so glitch power is not in the VCD.

The output is a build artefact, not a source file, and is not committed.

    tools/strip_specify.py <in.v> [<in.v> ...] --out-dir build/pdk/models
"""

from __future__ import annotations

import argparse
import pathlib
import re


SPECIFY_RE = re.compile(r"^[ \t]*specify\b.*?^[ \t]*endspecify[ \t]*\n", re.S | re.M)
MODULE_RE = re.compile(r"(^module\s+\w+\b.*?^endmodule)", re.S | re.M)
DELAYED_RE = re.compile(r"\bdelayed_(\w+)\b")
WIRE_DECL_RE = re.compile(r"^([ \t]*wire\b[^;]*\bdelayed_\w+[^;]*;)[ \t]*$", re.M)


def fix_module(body: str) -> tuple[str, int]:
    """Strip the specify block and drive every delayed_* net from its real port."""
    body, removed = SPECIFY_RE.subn("", body)
    if not removed:
        return body, 0

    names = sorted(set(DELAYED_RE.findall(body)))
    if not names:
        return body, removed

    assigns = "".join(f"\tassign delayed_{n} = {n};\n" for n in names)
    injection = ("\n\t// delayed_* nets were driven by the removed timing checks.\n"
                 "\t// Zero-delay equivalents keep the cell functional.\n" + assigns)

    match = WIRE_DECL_RE.search(body)
    if match:
        return body[:match.end()] + "\n" + injection + body[match.end():], removed
    # No matching wire declaration: put the assignments just before endmodule.
    index = body.rfind("endmodule")
    return body[:index] + injection + body[index:], removed


def strip(text: str) -> tuple[str, int]:
    """Rewrite every module in the file, returning the specify block count removed."""
    total = 0

    def replace(match: re.Match) -> str:
        nonlocal total
        fixed, removed = fix_module(match.group(1))
        total += removed
        return fixed

    return MODULE_RE.sub(replace, text), total


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("inputs", nargs="+", type=pathlib.Path)
    parser.add_argument("--out-dir", type=pathlib.Path, required=True)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for path in args.inputs:
        text = path.read_text()
        stripped, count = strip(text)
        out = args.out_dir / path.name
        header = (
            f"// Generated by tools/strip_specify.py from {path}\n"
            f"// {count} specify block(s) removed so Icarus Verilog can parse these\n"
            f"// models, and every delayed_* net driven from its real port so the\n"
            f"// cells still function. Only pin-to-pin delay annotation is lost, and\n"
            f"// this flow is zero-delay regardless.\n"
        )
        out.write_text(header + stripped)
        print(f"{path.name}: removed {count} specify blocks -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
